# Generated by Django 4.2.6 on 2023-10-22 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rating_wishlist_remove_savedhotel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='updateAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
