# Generated by Django 4.2.5 on 2023-10-27 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userpreferences_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinghotel',
            old_name='hotelName',
            new_name='hotelID',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='hotelName',
            new_name='hotelID',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='hotelName',
            new_name='hotelID',
        ),
        migrations.RemoveField(
            model_name='bookinghotel',
            name='id',
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='booking_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
