# Generated by Django 4.2.5 on 2023-10-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_hotelname_bookinghotel_hotelid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghotel',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
