# Generated by Django 4.2.5 on 2023-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_bookinghotel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghotel',
            name='date_return',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
