# Generated by Django 4.2.5 on 2023-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_bookinghotel_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
