# Generated by Django 4.2.5 on 2023-11-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_userpreferences_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghotel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userprofile'),
        ),
    ]
