# Generated by Django 4.2.5 on 2023-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_bookinghotel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinghotel',
            old_name='hotelID',
            new_name='roomId',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='hotelID',
            new_name='roomId',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='hotelID',
            new_name='roomId',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
