# Generated by Django 4.2.5 on 2023-11-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_hotelid_bookinghotel_roomid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='date_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinghotel',
            name='date_return',
            field=models.DateTimeField(null=True),
        ),
    ]
